### PR TITLE
Static framework target for iOS to enable Carthage support

### PR DESCRIPTION
**Pull request by nidegen**
Some questions to @lmirosevic:

- Should we remove the static lib target?
- What about merging osx/ios frameworks completely, just using target conditional macros? i think carthage would enjoy that.
- Should we officially add carthage support info in readme?

### CODE REVIEW

**Comment by nidegen** [comment]
hmm, another question: 

i have troubles using it with the precompiled headers. ok if i'd drop them? thanks

**Comment by nidegen** [comment]
or: do you insist on it being static at all? a shared fw would also be nice

**Comment by lmirosevic** [comment]
@nidegen Thanks for this PR! I'd love the Carthage support.

I'm OK with dropping the PCH.

I also don't insist on the lib being static. But please keep in mind though that GBJailbreakDetection is a closed source dependency of this lib, which is itself a static library. Jailbreak detection shouldn't break.

**Comment by nidegen** [comment]
@lmirosevic current status:
- Made a static fw for iOS, rm static lib target
- Builds with Carthage, has a run script that downloads the JailbreakDetection

Open:
- Test with CocoaPods. i have barely any experience with it. Can you maybe test it?
- We could also merge the OSX target and the iOS with some `#ifdefs`. I think it would make it cleaner, but not sure how this is compatible with CocoaPods. What do you think?

**Comment by santogioia** [comment]
what is the status of this PR?

**Comment by eduardbosch** [comment]
Any updates on this?

**Comment by lmirosevic** [comment]
Getting Carthage support would be great. Is there anyone who is happy to bring this PR over the finishing line, and I would merge it into master?

**Pull request closed without merging**
