### PR TITLE
 MOD: give pixelperinch a useful default value.

### PR DESCRIPTION
**Pull request by AntiMoron**
As title.

### CODE REVIEW

**Comment by lmirosevic** [comment]
Hi @antimoron thanks for the PR. And sorry for the late response. 

Can you help me understand the basis of this calculation? I don’t quite see the link between the height of a line of text and the screen’s physical properties.

**Comment by AntiMoron** [comment]
@lmirosevic  Hi, It's been claimed that 72pt is 1 inch. So 72pt system font's line height is approximately equal to 1 inch.

**Comment by lmirosevic** [comment]
Sounds like a reasonable fallback. Merging...

**Comment by lmirosevic** [comment]
Published as `5.4.0`. Thanks for the PR @AntiMoron !

**Pull request merged**
