### PR TITLE
added ppi calc to OSX

### PR DESCRIPTION
**Pull request by tesch1**
this shoudl be about right...  Also added the headers to the framework target.

### CODE REVIEW

**Comment by lmirosevic** [comment]
@tesch1 Thanks for the PR. I've updated your code a bit to reflect non square pixels (it's possible), and hidpi displays.

Please let me know if that works for your use case, and I will merge

**Comment by tesch1** [comment]
Great! 

(small pedantry comment, it's your project, but - sqrt is probably slightly faster than pow, and I would personally use *25.4 since it's more recognizeable and succinct :)

**Comment by lmirosevic** [comment]
Done

**Comment by lmirosevic** [comment]
Were good suggestions thanks!

I've cut a new release with this included: `5.1.0`

**Pull request merged**
