### PR TITLE
add iphone 15, 15 plus, 15 pro, 15 pro max models

### PR DESCRIPTION
**Pull request by marchbold**

### CODE REVIEW

**Comment by cpsauer** [comment]
Thanks for doing, Michael! Closing only because #147 beat you to it.

**Comment by marchbold** [comment]
Ah! Missed that! :)

**Comment by cpsauer** [comment]
Thanks for being eager to contribute! We'd of course love your help as new devices come out in the future, either iOS (like this) or macOS (because the device IDs are now ambiguous--see https://github.com/lmirosevic/GBDeviceInfo/pull/146).

For my learning (newly got write access): What are you building with this library and using it for? How do you bring it and other deps into your project, if not cocoapods?

**Comment by marchbold** [comment]
We use this library in a custom native extension for several AIR iOS applications we develop. We don't use cocoapods as it doesn't play nicely with our AIR build processes so we just have manual scripts that pull in this dependency directly.

**Comment by cpsauer** [comment]
Cool! If okay to share: anything more I should know about how you use it in those apps?

(You're also the first person I know who develops on AIR--curious what you think of it. We also use a different build route, Bazel.)

**Comment by marchbold** [comment]
Probably the biggest use is just the db of dpi, so we can switch assets used for our games to ensure we are using appropriate quality textures etc.

Regarding AIR we find it a great platform for developing 2D games, particularly now it has a new development team behind the SDK, it's been moving really quickly again.

**Comment by cpsauer** [comment]
And how do you handle new/unknown devices? (Internally we have a server we hit--curious if that's something people are doing more generally.)

**Comment by marchbold** [comment]
No generally we just use the screen size and have a best guess.

**Pull request closed without merging**
