### PR TITLE
Add iphone 15 family

### PR DESCRIPTION
**Pull request by rus1km**

### CODE REVIEW

**Comment by cpsauer** [comment]
Beat me to it! Thanks for doing. @lmirosevic, LGTM
(Though it might be worth also adding to README?)

**Comment by hamidjan** [comment]
Please merge this pull request. It seems to be necessary

**Comment by cpsauer** [comment]
(To clarify, I don't have merging power--was just trying to streamline the process of getting it in. Haven't heard from the repo owner in a little while, but he's been very responsive in the past.)

**Comment by hamidjan** [comment]
thanks for your reply @cpsauer. I hope the owner consider the merging soon as its very important

**Comment by cpsauer** [comment]
Got write permissions :) Done!

**Pull request merged**
