### PR TITLE
Adding iPad 7 (2017 model) new 12p9Inch and 10p5Inch

### PR DESCRIPTION
**Pull request by Yelles**
Hi,

could you accept this pull request for the new iPad Pro 12,9 and 10,5.

### CODE REVIEW

**Comment by lmirosevic** [comment]
Thanks for the PR.

One issue, the new iPad Pro 12.9 is not the same device as the old 12.9 inch iPad. This one will need a different identifier

**Comment by Yelles** [comment]
I see, may be GBDeviceModeliPadPro12p9Inch2 ?

**Comment by lmirosevic** [comment]
Yeah, I think `GBDeviceModeliPadPro12p9Inch2`and `GBDeviceModeliPadPro10p5Inch2` will do.

**Comment by vGubriienko** [comment]
Any updates on this PR?

**Comment by lmirosevic** [comment]
@Yelles Did you want to update your PR, then I can merge it

**Comment by rist** [comment]
hi - as we are still missing iPad Pro 2017 - @Yelles can you update the PR or @lmirosevic should I create a new PR with basically the same change plus the renaming to finally get these devices covered?

**Comment by lmirosevic** [comment]
@rist That would be great if you could do that. I will merge right away then

**Comment by lmirosevic** [comment]
Merged in #75 

I've cut a new release with this included: `5.1.0`

**Pull request closed without merging**
