### PR TITLE
Fixed #22

### LINKED ISSUE #22: Incorrect Device Info for OSX 10.10.1 - Minor OS Version
Hi, I noticed that your OS X operating system version info comes by way of a uname call.  It looks like the Darwin kernel information is not a reliable way to do this, at least as of Yosemite .1.

On various 10.10.1 Macs we all see:

    mymac:~ me$ uname -a
    Darwin mymac 14.0.0 Darwin Kernel Version 14.0.0: Fri Sep 19 00:26:44 PDT 2014; root:xnu-2782.1.97~2/RELEASE_X86_64 x86_64

Which is consistent with the 0 minor os version returned by GBDeviceInfo.

May I suggest basing your version string on the system version plist instead?  Something like:

    NSString *systemVersion = [NSDictionary dictionaryWithContentsOfFile:@"/System/Library/CoreServices/SystemVersion.plist"][@"ProductUserVisibleVersion"];

### PR DESCRIPTION
**Pull request by stefanhp**
Used @rolandhordos suggestion: system version is now fetched from SystemVersion.plist.

Signed-off-by: Stefan Paychère <stefan.paychere@epyx.ch>

### CODE REVIEW

**Comment by lmirosevic** [comment]
is this sandbox, i.e. Mac App Store safe?

**Comment by stefanhp** [comment]
I did not think of that, probably not...
I'll do another version using NSProcessInfo.

**Comment by stefanhp** [comment]
Well I'm not sure what to do:
- ```Gestalt(gestaltSystemVersionMajor, &majorVersion)``` was the way to do this, but it's deprecated since 10.8
- ```NSProcessInfo:operatingSystemVersion``` is the new proper way of doing this, but it only appeared in 10.10.

Would you be ok with something like:
```
#if __MAC_OS_X_VERSION_MIN_REQUIRED >= 101000
    NSOperatingSystemVersion osVersion = [[NSProcessInfo processInfo] operatingSystemVersion];
        majorOSVersionInteger = osVersion.majorVersion;
        minorOSVersionInteger = osVersion.minorVersion;
        patchOSVersionInteger = osVersion.patchVersion;
#else
    SInt32 majorVersion, minorVersion, patchVersion;
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"
    Gestalt(gestaltSystemVersionMajor, &majorVersion);
    Gestalt(gestaltSystemVersionMinor, &minorVersion);
    Gestalt(gestaltSystemVersionBugFix, &patchVersion);
#pragma clang diagnostic pop
        majorOSVersionInteger = majorVersion;
        minorOSVersionInteger = minorVersion;
        patchOSVersionInteger = patchVersion;
#endif
```

**Comment by lmirosevic** [comment]
That seems like the only reasonable approach.

I would however make the check at runtime rather than at compile time. Why? Because if Apple decides to remove the Gestalt call in the next version of OS X, and the library is built with a minimum target which is older than 10.10, then it will crash.

So I'd write it like this:
```
if ([[NSProcessInfo processInfo] respondsToSelector:@selector(operatingSystemVersion)]) {
    NSOperatingSystemVersion osVersion = [[NSProcessInfo processInfo] operatingSystemVersion];

    majorOSVersionInteger = osVersion.majorVersion;
    minorOSVersionInteger = osVersion.minorVersion;
    patchOSVersionInteger = osVersion.patchVersion;
}
else {
    SInt32 majorVersion, minorVersion, patchVersion;

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"
    Gestalt(gestaltSystemVersionMajor, &majorVersion);
    Gestalt(gestaltSystemVersionMinor, &minorVersion);
    Gestalt(gestaltSystemVersionBugFix, &patchVersion);
#pragma clang diagnostic pop

    majorOSVersionInteger = majorVersion;
    minorOSVersionInteger = minorVersion;
    patchOSVersionInteger = patchVersion;
}
```

**Comment by lmirosevic** [comment]
Fixed in b237f1bd1129ec7c11ae572cb0b6443caf4454bd

**Comment by lmirosevic** [comment]
Now on cocaapods as 3.0.0

**Pull request closed without merging**
